use_frameworks!

platform :ios, '9.0'

target 'YDNetwork_Example' do
  pod 'YDNetwork', :podspec => '../YDNetwork.podspec'

  target 'YDNetwork_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
