use_frameworks!

platform :ios, '8.0'

target 'YDNetwork_Example' do
  pod 'YDNetwork', :path => '../'

  target 'YDNetwork_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
